version: '3'

includes:
  back:
    taskfile: ./back/Taskfile.yml
    dir: ./back
  front:
    taskfile: ./front/Taskfile.yml
    dir: ./front
  doc:
    taskfile: ./doc/Taskfile.yml
    dir: ./doc
tasks:
  default:
    cmds:
      - task --list-all
  hello:
    cmds:
      - echo "Bonjour à vous mes très chers amis !"
  install_nix_linux:
    cmds:
      - sh <(curl -L https://nixos.org/nix/install) --daemon
  install_nix_windows:
    cmds:
      - sh <(curl -L https://nixos.org/nix/install) --no-daemon
  install_nix_mac:
    cmds:
      - sh <(curl -L https://nixos.org/nix/install)
  serve_back:
    cmds:
      - task: back:auto_serve
  serve_front:
    cmds:
      - task: front:auto_serve
  serve_doc:
    cmds:
      - task: doc:auto_serve
  clean_container:
    cmds:
      - docker stop $(docker ps -a -q)
      - docker container prune
      - docker volume prune  
  clean_docker_images:
    cmds: 
      - docker rmi -f $(docker images -aq)
  clean_docker: 
    cmds:
      - task: clean_container
      - task: clean_docker_images
  run_docker:
    dir: deploy
    cmds:
      - docker compose up -d
  fresh_start_docker:
    cmds:
      - task: back:build_docker_img
      - task: front:build_docker_img
      - task: run_docker

