package open.tresorier.utils

enum class PropertiesEnum {
    TRESORIER_DB_URL_DFLT,
    TRESORIER_DB_USR_DFLT,
    TRESORIER_DB_PWD_DFLT,

    TEST_DB_URL,
    TEST_DB_USR,
    TEST_DB_PWD,

    INTEGRATION_DB_URL_DFLT,
    INTEGRATION_DB_USR_DFLT,
    INTEGRATION_DB_PWD_DFLT,

    TRESORIER_DB_URL,
    TRESORIER_DB_USR,
    TRESORIER_DB_PWD,

    INTEGRATION_DB_URL,
    INTEGRATION_DB_USR,
    INTEGRATION_DB_PWD,

    ALLOWED_ORIGIN_FRONT,
    ALLOWED_ORIGIN_LOCALHOST,
    ALLOWED_ORIGIN_BETA_FRONT,
    ALLOWED_ORIGIN_STRIPE,
    
    ENVIRONMENT,

    TRESORIER_DB_ID,
    INTEGRATION_DB_ID,

    STRIPE_API_KEY,
    STRIPE_WEBHOOK,
    
    MONTHLY_INTEGRAL,
    ANNUAL_INTEGRAL,
    MONTHLY_ESSENTIAL,
    ANNUAL_ESSENTIAL,
    MONTHLY_COMPANY,
    ANNUAL_COMPANY,

    TAX_ID,
    SUCCES_URL,
    CANCEL_URL,

    AWEBER_LIST_ID,
    AWEBER_ACCOUNT_ID,
    AWEBER_ACCESS_TOKEN,
    AWEBER_REFRESH_TOKEN,
    AWEBER_CLIENT_ID,

    NORDIGEN_SECRET_ID,
    NORDIGEN_SECRET_KEY,
    NORDIGEN_SUCCESS_URL,

    KEYCLOAK_ID,
    KEYCLOAK_SECRET,
    KEYCLOAK_REALM,
    KEYCLOAK_DISC_URI,
    KEYCLOAK_BASE_URI,

    API_BASE_URL,
    REDIRECT_URI
}