version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  hello:
    cmds:
      - echo "Bonjour à vous mes très chers amis !"
  serve:
    cmds:
      - gradle migrate
      - gradle run
  test:
    cmds:
      - gradle test
  jar:
    cmds:
      - gradle uberjar
  run_jar:
    cmds:
      - task: jar
      - java -jar -Dlogback.configurationFile=logback.xml build/libs/agatha-backend-uber.jar
  import_sql:
    desc: task import_sql PATH=path_to_file (/!\ replace all role by postgres in the file beforehand)
    cmds:
      - pg_ctl restart 
      - dropdb -h localhost -U postgres agatha
      - createdb -h localhost -U postgres agatha
      - cp {{.PATH}} imported_backup.sql
      - sed -i -e 's/szigudsebbcgip/postgres/g' imported_backup.sql
      - psql -h localhost -U postgres -d agatha -f imported_backup.sql
      - rm imported_backup.sql
      - pg_ctl restart 
  auto_serve:
    desc: serve backend from scratch
    cmds:
      - nix-shell --pure --command "task serve"
  build_nix_package:
    cmds: 
      - task: jar
      - nix-build deploy/back.nix
  build_docker_img:
    cmds:
      - nix-build deploy/docker.nix 
      - docker load < result
  run_docker:
    desc: --mount -> link the properties file to the container, --net=host -> use same port dans access the databse
    cmds:
      - docker run --mount type=bind,source="$(pwd)/gradle.properties",target=/home/gradle.properties --net=host agatha-back-image:latest
  fresh_start_docker:
    cmds:
      - task: build_docker_img
      - task: run_docker
  clean_docker:
    cmds:
      - docker container prune
      - docker rmi -f $(docker images -aq)