version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  hello:
    cmds:
      - echo "Bonjour à vous mes très chers amis !"
  serve:
    cmds:
      - gradle migrate
      - gradle run
  test:
    cmds:
      - gradle test
  jar:
    cmds:
      - gradle uberjar
  run_jar:
    cmds:
      - task: jar
      - java -jar -Dlogback.configurationFile=logback.xml build/libs/agatha-backend-uber.jar
  import_sql:
    desc: task import_sql PATH=path_to_file (/!\ replace all role by postgres in the file beforehand)
    cmds:
      - pg_ctl restart 
      - dropdb -h localhost -U postgres agatha
      - createdb -h localhost -U postgres agatha
      - cp {{.PATH}} imported_backup.sql
      - sed -i -e 's/szigudsebbcgip/postgres/g' imported_backup.sql
      - psql -h localhost -U postgres -d agatha -f imported_backup.sql
      - rm imported_backup.sql
      - pg_ctl restart 
  auto_serve:
    desc: serve backend from scratch
    cmds:
      - nix-shell --pure --command "task serve"
  build_nix_package:
    cmds: 
      - nix-build deploy/back.nix
  build_docker_img:
    cmds:
      - nix-build deploy/docker.nix ; echo $?
      - docker image load -i /nix/store/792xalvdr8m9vy172nrk02c8yzr8zmr7-agatha-back-image.tar.gz
  run_docker:
    cmds:
      - docker run --mount type=bind,source=./gradle.properties,target=/home/gradle.properties:ro agatha-back-image:latest
  fresh_start_docker:
    cmds:
      - task: build_docker_img
      - task: run_docker
