services:

  agatha-db:
    image: agatha-db-image:latest
    environment:
      POSTGRES_PASSWORD: agatha-db-password
      POSTGRES_USER: postgres
      POSTGRES_DB: agatha
    ports:
      - 4321:5432    #HOST:CONTAINER
    volumes:
      - ../back/db/postgres-data:/var/lib/postgresql/data

  agatha-back:
    image: agatha-back-image:latest
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ../back/deploy/gradle.properties
        target: /home/gradle.properties
    depends_on:
      - agatha-db

  agatha-front:
    image: agatha-front-image:latest
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ../front/deploy/nginx.conf
        target: /home/conf/nginx.conf
      - ../front/deploy/nginx:/var/log/nginx/
    depends_on:
      - agatha-back