version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  serve:
    cmds:
      - bundle exec jekyll serve
  auto_serve: 
    cmds:
      - nix-shell --pure --command "bundle install && task serve"
  
